#if !canImport(ObjectiveC)
  import XCTest

  extension OptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionsTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(OptionsTests.__allTests__OptionsTests)
    ]
  }
#endif
