//
//  XCTestManifests.swift
//  SimulatorServices
//
//  Created by Leo Dion.
//  Copyright © 2024 BrightDigit.
//
//  Permission is hereby granted, free of charge, to any person
//  obtaining a copy of this software and associated documentation
//  files (the “Software”), to deal in the Software without
//  restriction, including without limitation the rights to use,
//  copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following
//  conditions:
//
//  The above copyright notice and this permission notice shall be
//  included in all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
//  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
//  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//  OTHER DEALINGS IN THE SOFTWARE.
//

#if !canImport(ObjectiveC)
  import XCTest

  extension EnumSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumSetTests = [
      ("testArray", testArray),
      ("testDecoder", testDecoder),
      ("testEncoder", testEncoder),
      ("testInitValue", testInitValue),
      ("testInitValues", testInitValues)
    ]
  }

  extension MappedEnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MappedEnumTests = [
      ("testDecoder", testDecoder),
      ("testEncoder", testEncoder)
    ]
  }

  extension MappedValueCollectionRepresentedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MappedValueCollectionRepresentedTests = [
      ("testRawValue", testRawValue),
      ("testRawValueFailure", testRawValueFailure),
      ("testString", testString),
      ("testStringFailure", testStringFailure)
    ]
  }

  extension MappedValueDictionaryRepresentedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MappedValueDictionaryRepresentedTests = [
      ("testRawValue", testRawValue),
      ("testRawValueFailure", testRawValueFailure),
      ("testString", testString),
      ("testStringFailure", testStringFailure)
    ]
  }

  extension MappedValueRepresentableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MappedValueRepresentableTests = [
      ("testStringValue", testStringValue)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(EnumSetTests.__allTests__EnumSetTests),
      testCase(MappedEnumTests.__allTests__MappedEnumTests),
      testCase(MappedValueCollectionRepresentedTests.__allTests__MappedValueCollectionRepresentedTests),
      testCase(MappedValueDictionaryRepresentedTests.__allTests__MappedValueDictionaryRepresentedTests),
      testCase(MappedValueRepresentableTests.__allTests__MappedValueRepresentableTests)
    ]
  }
#endif
